runtime: nodejs10

# This MUST be the last line of this file so that deploy.sh can add the API_KEY
# environment variable. You may ONLY include additional environment variables
# that need to be passed after the below env_variables line.
env_variables:
