before_script:
    - date
    - uname -a

frontend:
    image: node:13
    script:
    - cd frontend/
    - npm install --user
    - make test

backend:
    image: pets4me/backend
    script:
    - sudo /etc/init.d/postgresql start
    - make update-backend
    - make backend-test
