# Name of Service
service: backend

# From GCP tutorial: https://cloud.google.com/appengine/docs/standard/python3/building-app/deploying-web-service
# Code from: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard_python37/building-an-app/building-an-app-1/app.yaml

runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

# libraries:
#   - name: ssl
#     version: latest

